# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/ip/FFT_Zynq_fft_butterlfy_ip_0_1/FFT_Zynq_fft_butterlfy_ip_0_1.xci
# IP: The module: 'FFT_Zynq_fft_butterlfy_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Im_Factor_ROM_Memory/ip/Phase_Im_Factor_ROM_Memory/Phase_Im_Factor_ROM_Memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Phase_Im_Factor_ROM_Memory || ORIG_REF_NAME==Phase_Im_Factor_ROM_Memory} -quiet] -quiet

# IP: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Re_Factor_ROM_Memory/ip/Phase_Re_Factor_ROM_Memory/Phase_Re_Factor_ROM_Memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Phase_Re_Factor_ROM_Memory || ORIG_REF_NAME==Phase_Re_Factor_ROM_Memory} -quiet] -quiet

# XDC: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Im_Factor_ROM_Memory/ip/Phase_Im_Factor_ROM_Memory/Phase_Im_Factor_ROM_Memory_ooc.xdc

# XDC: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Re_Factor_ROM_Memory/ip/Phase_Re_Factor_ROM_Memory/Phase_Re_Factor_ROM_Memory_ooc.xdc

# IP: C:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/ip/FFT_Zynq_fft_butterlfy_ip_0_1/FFT_Zynq_fft_butterlfy_ip_0_1.xci
# IP: The module: 'FFT_Zynq_fft_butterlfy_ip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Im_Factor_ROM_Memory/ip/Phase_Im_Factor_ROM_Memory/Phase_Im_Factor_ROM_Memory.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Phase_Im_Factor_ROM_Memory || ORIG_REF_NAME==Phase_Im_Factor_ROM_Memory} -quiet] -quiet

# IP: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Re_Factor_ROM_Memory/ip/Phase_Re_Factor_ROM_Memory/Phase_Re_Factor_ROM_Memory.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Phase_Re_Factor_ROM_Memory || ORIG_REF_NAME==Phase_Re_Factor_ROM_Memory} -quiet] -quiet

# XDC: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Im_Factor_ROM_Memory/ip/Phase_Im_Factor_ROM_Memory/Phase_Im_Factor_ROM_Memory_ooc.xdc

# XDC: c:/Users/Vrael/Desktop/FFT_Project/module_sim/fft_module/fft_module.srcs/sources_1/bd/FFT_Zynq/fft_module/fft_module.srcs/Phase_Re_Factor_ROM_Memory/ip/Phase_Re_Factor_ROM_Memory/Phase_Re_Factor_ROM_Memory_ooc.xdc
