# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FFT_Microblaze/FFT_Microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze || ORIG_REF_NAME==FFT_Microblaze} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_FFT_Butterfly_Axi_Li_0_0/FFT_Microblaze_FFT_Butterfly_Axi_Li_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_FFT_Butterfly_Axi_Li_0_0 || ORIG_REF_NAME==FFT_Microblaze_FFT_Butterfly_Axi_Li_0_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_microblaze_0_0/FFT_Microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_microblaze_0_0 || ORIG_REF_NAME==FFT_Microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_dlmb_v10_0/FFT_Microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_dlmb_v10_0 || ORIG_REF_NAME==FFT_Microblaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_ilmb_v10_0/FFT_Microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_ilmb_v10_0 || ORIG_REF_NAME==FFT_Microblaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_dlmb_bram_if_cntlr_0/FFT_Microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==FFT_Microblaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_ilmb_bram_if_cntlr_0/FFT_Microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==FFT_Microblaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_lmb_bram_0/FFT_Microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_lmb_bram_0 || ORIG_REF_NAME==FFT_Microblaze_lmb_bram_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_mdm_1_0/FFT_Microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_mdm_1_0 || ORIG_REF_NAME==FFT_Microblaze_mdm_1_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_clk_wiz_1_0/FFT_Microblaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_clk_wiz_1_0 || ORIG_REF_NAME==FFT_Microblaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_rst_clk_wiz_1_100M_0/FFT_Microblaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==FFT_Microblaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/FFT_Microblaze/ip/FFT_Microblaze_microblaze_0_axi_periph_0/FFT_Microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==FFT_Microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: bd/FFT_Microblaze/FFT_Microblaze_ooc.xdc
