webtalk_init -webtalk_dir D:\\addam\\Git\\SDUP\\zynq_fft_ip_core\\module_sim\\fft_module\\fft_module.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-06-12 18:19:25" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9elv8e7nt7gp05ua6u292rtvs8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 2700X Eight-Core Processor         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3693 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.277 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1623513230454" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1623513230454"
webtalk_add_data -client sdk -key uid -value "1623513253783" -context "sdk\\\\bsp/1623513253783"
webtalk_add_data -client sdk -key hwid -value "1623513230454" -context "sdk\\\\bsp/1623513253783"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1623513253783"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1623513253783"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1623513253783"
webtalk_add_data -client sdk -key uid -value "1623513255022" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key hwid -value "1623513230454" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key bspid -value "1623513253783" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key projSize -value "236.234375" -context "sdk\\\\application/1623513255022"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key DebugCount -value "13" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1623514765746"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1623514765746"
webtalk_transmit -clientid 507597943 -regid "" -xml D:\\addam\\Git\\SDUP\\zynq_fft_ip_core\\module_sim\\fft_module\\fft_module.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\addam\\Git\\SDUP\\zynq_fft_ip_core\\module_sim\\fft_module\\fft_module.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\addam\\Git\\SDUP\\zynq_fft_ip_core\\module_sim\\fft_module\\fft_module.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
