Zeros = zeros(1,16);
Ones = ones(1,16);
Square = [1, 0,1, 0,1, 0,1, 0,1, 0,1, 0,1, 0,1, 0];
t = 15;
dt = 0:1:t;
Cos = cos(2*pi*dt/t);
Sin = sin(2*pi*dt/t);
writematrix(dec2bin(Zeros), 'Input_Vectors.csv','Delimiter',' ');
writematrix(dec2bin(Ones), 'Input_Vectors.csv','Delimiter',' ','WriteMode', 'append');
writematrix(dec2bin(Square), 'Input_Vectors.csv','Delimiter',' ','WriteMode',' ','WriteMode', 'append');
%writematrix(Cos, 'Input_Vectors.csv','Delimiter',' ','WriteMode',' ','WriteMode', 'append');
%writematrix(Sin, 'Input_Vectors.csv','Delimiter',' ','WriteMode',' ','WriteMode', 'append');
FFT_Zeros = fft(Zeros);
FFT_Ones = fft(Ones);
FFT_Square = fft(Square);
FFT_Cos = fft(Cos);
FFT_Sin = fft(Sin);
writematrix(dec2bin(FFT_Zeros), 'Output_Vectors.csv','Delimiter',' ');
writematrix(dec2bin(FFT_Ones), 'Output_Vectors.csv','Delimiter',' ','WriteMode', 'append');
writematrix(dec2bin(FFT_Square), 'Output_Vectors.csv','Delimiter',' ','WriteMode', 'append');
%writematrix(FFT_Cos, 'Output_Vectors.csv','Delimiter',' ','WriteMode', 'append');
%writematrix(FFT_Sin, 'Output_Vectors.csv','Delimiter',' ','WriteMode', 'append');
