# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/FFT_Zynq_Axi_Lite/FFT_Zynq_Axi_Lite.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite || ORIG_REF_NAME==FFT_Zynq_Axi_Lite} -quiet] -quiet

# IP: bd/FFT_Zynq_Axi_Lite/ip/FFT_Zynq_Axi_Lite_FFT_Butterfly_Axi_Li_0_0/FFT_Zynq_Axi_Lite_FFT_Butterfly_Axi_Li_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite_FFT_Butterfly_Axi_Li_0_0 || ORIG_REF_NAME==FFT_Zynq_Axi_Lite_FFT_Butterfly_Axi_Li_0_0} -quiet] -quiet

# IP: bd/FFT_Zynq_Axi_Lite/ip/FFT_Zynq_Axi_Lite_processing_system7_0_0/FFT_Zynq_Axi_Lite_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite_processing_system7_0_0 || ORIG_REF_NAME==FFT_Zynq_Axi_Lite_processing_system7_0_0} -quiet] -quiet

# IP: bd/FFT_Zynq_Axi_Lite/ip/FFT_Zynq_Axi_Lite_ps7_0_axi_periph_0/FFT_Zynq_Axi_Lite_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite_ps7_0_axi_periph_0 || ORIG_REF_NAME==FFT_Zynq_Axi_Lite_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FFT_Zynq_Axi_Lite/ip/FFT_Zynq_Axi_Lite_rst_ps7_0_100M_0/FFT_Zynq_Axi_Lite_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite_rst_ps7_0_100M_0 || ORIG_REF_NAME==FFT_Zynq_Axi_Lite_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/FFT_Zynq_Axi_Lite/ip/FFT_Zynq_Axi_Lite_auto_pc_0/FFT_Zynq_Axi_Lite_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Zynq_Axi_Lite_auto_pc_0 || ORIG_REF_NAME==FFT_Zynq_Axi_Lite_auto_pc_0} -quiet] -quiet

# XDC: bd/FFT_Zynq_Axi_Lite/FFT_Zynq_Axi_Lite_ooc.xdc
