# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# Block Designs: bd/FFT_Butterfly_Zynq/FFT_Butterfly_Zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq || ORIG_REF_NAME==FFT_Butterfly_Zynq} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0/FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_processing_system7_0_0/FFT_Butterfly_Zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_processing_system7_0_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_auto_pc_0/FFT_Butterfly_Zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_auto_pc_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_auto_pc_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_ps7_0_axi_periph_0/FFT_Butterfly_Zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_rst_ps7_0_100M_0/FFT_Butterfly_Zynq_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_rst_ps7_0_100M_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/FFT_Butterfly_Zynq/FFT_Butterfly_Zynq_ooc.xdc
