# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# Block Designs: bd/FFT_Butterfly_Microblaze/FFT_Butterfly_Microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze || ORIG_REF_NAME==FFT_Butterfly_Microblaze} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_FFT_Butterfly_Axi_Li_0_0/FFT_Butterfly_Microblaze_FFT_Butterfly_Axi_Li_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_FFT_Butterfly_Axi_Li_0_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_FFT_Butterfly_Axi_Li_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_microblaze_0_0/FFT_Butterfly_Microblaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_microblaze_0_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_microblaze_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_dlmb_v10_0/FFT_Butterfly_Microblaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_dlmb_v10_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_ilmb_v10_0/FFT_Butterfly_Microblaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_ilmb_v10_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_dlmb_bram_if_cntlr_0/FFT_Butterfly_Microblaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_ilmb_bram_if_cntlr_0/FFT_Butterfly_Microblaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_lmb_bram_0/FFT_Butterfly_Microblaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_lmb_bram_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_lmb_bram_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_mdm_1_0/FFT_Butterfly_Microblaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_mdm_1_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_mdm_1_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_clk_wiz_1_0/FFT_Butterfly_Microblaze_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_clk_wiz_1_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_clk_wiz_1_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_rst_clk_wiz_1_100M_0/FFT_Butterfly_Microblaze_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Microblaze/ip/FFT_Butterfly_Microblaze_microblaze_0_axi_periph_0/FFT_Butterfly_Microblaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Microblaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==FFT_Butterfly_Microblaze_microblaze_0_axi_periph_0} -quiet] -quiet

# Block Designs: bd/FFT_Butterfly_Zynq/FFT_Butterfly_Zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq || ORIG_REF_NAME==FFT_Butterfly_Zynq} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0/FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_FFT_Butterfly_Axi_Li_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_processing_system7_0_0/FFT_Butterfly_Zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_processing_system7_0_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_auto_pc_0/FFT_Butterfly_Zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_auto_pc_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_auto_pc_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_ps7_0_axi_periph_0/FFT_Butterfly_Zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/FFT_Butterfly_Zynq/ip/FFT_Butterfly_Zynq_rst_ps7_0_100M_0/FFT_Butterfly_Zynq_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FFT_Butterfly_Zynq_rst_ps7_0_100M_0 || ORIG_REF_NAME==FFT_Butterfly_Zynq_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/FFT_Butterfly_Microblaze/FFT_Butterfly_Microblaze_ooc.xdc

# XDC: bd/FFT_Butterfly_Zynq/FFT_Butterfly_Zynq_ooc.xdc
